### ISSUE TITLE
aborted download if some songs in album are out of service

### ISSUE THREAD

**Issue by kanyevelvet** [WHTJEON/genie-music-downloader#1]
앨범중 일부곡이 음원사이트에 내려간게 있으면, 다운로드가 중단됩니다.

**Comment by WHTJEON** [comment]
그 부분에 대한 처리를 했던 것 같은데.. 혹시 그러한 앨범 아무거나 하나만 알려주실수 있나요?

**Comment by kanyevelvet** [comment]
https://www.genie.co.kr/detail/albumInfo?axnm=81603454 이건 안되는데
https://www.genie.co.kr/detail/albumInfo?axnm=81973814 이건 되네요.

**Comment by WHTJEON** [comment]
확인해보고 수정하여 업데이트하겠습니다.

**Comment by WHTJEON** [comment]
혹시 최신 버전으로 업데이트 하셨나요? 위의 앨범으로 방금 해봤는데 오류 없이 잘 다운되네요.. 다만 장윤정 BEST 20 저 앨범 같은 경우는 트랙이 5개씩 두개의 CD로 나눠져 올라가있는데 CD가 여러개로 나뉘어진 앨범의 다운로드 로직을 어떻게 처리할지 아직 좋은 방법을 찾지 못해 일단은 CD1만 다운로드가 되도록 해놓은 상황입니다. 이 부분 역시 추후 업데이트로 수정할 계획입니다.

**Comment by kanyevelvet** [comment]
지니뮤직이 disc 구분 없이 1번부터 n번까지 정렬화 해놓아서 저 앨범이 2CD로 구분되어 있는지 몰랐습니다. 
제가 readme에서 멀티디스크 개선 한다고 한건 봤었는데.......ㅠㅠㅋㅋㅋ 어쨌든 감사합니다. 앞으로 업데이트 보수도 기대하겠습니다.

**Comment by WHTJEON** [comment]
넵넵! 혹시 원하시는 기능 있으시면 자유롭게 말씀해주시면 최대한 반영하겠습니다
